---
title: "Master Test 18.02."
format: html
editor: visual
---

```{r}
# readxl for å lese excel-fil
library(readxl)
# httr og jsonlite for å suge inn API
library(httr)
library(jsonlite)
```

## Tittel

En test av innlasting av data fra Eiendomsverdi (EV)

```{r}
EV <- read_excel("~/Library/CloudStorage/Dropbox/Master i økonomi og administrasjon/MSB210 Masteroppgave/Data/MSB210_Masteroppgave/data/EV-kommaseparert.xlsx")
head(EV)
```

En test av API-greiene

# Create request object with headers

```{r}
url <- "https://apim.p42.enova.no/ems/bank/v1/Fil/2021/01"
year <- "2021"
month <- "01"
request <- GET(sprintf(url, year = year, month = month), 
               add_headers("x-api-key" = "d9176773bbc14dab9ce5da9a38959af8"))

# Get response content as text
response_text <- content(request, as = "text", encoding = "UTF-8")

# Check if the response is successful and display the response content
if (status_code(request) == 200) {
  response_text <- content(request, as = "text")
  response_list <- fromJSON(response_text)
  print(response_list)
} else {
  print(paste0("Error: ", status_code(request), " - ", content(request, as = "text")))
}
```

# Convert response content from JSON to a list

```{r}
response_list <- fromJSON(response_text)
# View response list
response_list
```
